const API = 'https://kdramaapi.joshuaklein-malonda.workers.dev';
const PROXY = `${API}/proxy?url=`;

export function proxyStreamUrl(url) {
  return url.startsWith(PROXY) ? url : PROXY + encodeURIComponent(url);
}

// ponytail: the kkey is generated by kisskh's own player JS (browser-fingerprint
// encrypted, expires in seconds) — there is no public algorithm to replicate. The
// collector captures the already-authenticated stream URL from the user's live
// kisskh session (that URL carries the kkey), then hands it to the Worker's
// /proxy endpoint as the query param. Mirrors kissget's browser_collector.js.
export function collectorScript() {
  return `(function () {
  var API = ${JSON.stringify(API)};
  var PROXY = ${JSON.stringify(PROXY)};
  var seen = [];
  function capture(u) {
    if (seen.indexOf(u) > -1) return;
    seen.push(u);
    var p = PROXY + encodeURIComponent(u);
    var msg = '[kisskh] Stream captured \\u2014 paste into HallyuWave Watch page:\\n\\n' + p;
    try { navigator.clipboard.writeText(p); msg += '\\n\\n(copied to clipboard)'; } catch (e) {}
    alert(msg);
    try { localStorage.setItem('hallyuwave_stream', p); } catch (e) {}
  }
  try {
    new PerformanceObserver(function (l) {
      l.getEntries().forEach(function (e) {
        var u = e.name;
        if (u.indexOf('.m3u8') > -1 && u.indexOf(location.hostname) === -1) capture(u);
      });
    }).observe({ type: 'resource', buffered: true });
  } catch (e) {}
  var of = window.fetch;
  window.fetch = function () {
    var a = arguments;
    return of.apply(this, a).then(function (r) {
      var u = typeof a[0] === 'string' ? a[0] : (a[0] && a[0].url) || '';
      if (u.indexOf('/api/DramaList/Episode/') > -1) {
        r.clone().json().then(function (b) { if (b && b.Video) capture(b.Video); }).catch(function () {});
      }
      return r;
    });
  };
  var so = XMLHttpRequest.prototype.open;
  XMLHttpRequest.prototype.open = function (m, u) { this.__u = String(u); return so.apply(this, arguments); };
  var ss = XMLHttpRequest.prototype.send;
  XMLHttpRequest.prototype.send = function () {
    if (this.__u && this.__u.indexOf('/api/DramaList/Episode/') > -1) {
      this.addEventListener('load', function () {
        try { var b = JSON.parse(this.responseText); if (b && b.Video) capture(b.Video); } catch (e) {}
      });
    }
    return ss.apply(this, arguments);
  };
  alert('[kisskh] Collector installed \\u2014 open/refresh an episode to capture its stream URL.');
})();`;
}